tasks:
  - init: |
      brew install git-lfs
      git lfs install
      git lfs pull
    command: |
      echo 'hello gitpod workspace command'
      sleep 3600

github:
  prebuilds:
    branches: true
